# Generated by Django 4.2.19 on 2025-02-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstechou', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiboukou',
            options={'verbose_name': '志望校', 'verbose_name_plural': '志望校一覧'},
        ),
        migrations.RemoveField(
            model_name='shiboukou',
            name='name',
        ),
    ]
