# Generated by Django 4.2.19 on 2025-02-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstechou', '0002_alter_shiboukou_options_remove_shiboukou_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastexam',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='pastexam',
            name='score',
        ),
    ]
